# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20170425_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority']},
        ),
    ]
